# Generated by Django 3.2.16 on 2022-12-10 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='ims.product'),
        ),
    ]
