# Generated by Django 3.2.16 on 2022-12-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='labels',
            field=models.CharField(default='color, size, others', max_length=200),
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
