# Generated by Django 3.2.16 on 2022-12-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0008_auto_20221211_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='labels',
            field=models.JSONField(null=True),
        ),
    ]
