# Generated by Django 3.2.16 on 2023-02-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0011_rename_orderitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
